version: '3'

services:
  web:
    image: nginx
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.web.rule=Host('testeth.maue.tech')"
        - "traefik.http.routers.web.entrypoints=websecure"
        - "traefik.http.routers.web.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.web.loadbalancer.server.port=80"
networks:
  traefik-public:
    external: true