version: '3'

services:
  testeth:
    image: nginx
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.testeth.rule=Host(testeth.maue.tech)"
        - "traefik.http.routers.testeth.entrypoints=websecure"
        - "traefik.http.routers.testeth.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.testeth.loadbalancer.server.port=80"
networks:
  traefik-public:
    external: true